### PR TITLE
Support for AmpereOne family

### PR DESCRIPTION
**Pull request by binh-ampere**
#### Support for AmpereOne family
Ampere's newest processor, AmpereOne, has architecture-specific build options to improve performance through better code generation. This PR is aimed to detect software built for the Arm Neoverse series of processors and recommend options for AmpereOne support.

#### Add detection for meson build files
This PR support detects meson build files for missing AmpereOne support.

#### Other changes
Extend other arch list with loongarch64, riscv64, sandybridge, zen, etc to reduce noise.
UT cases extended.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by naren-ampere** [comment]
Bin,
I would recommend the following text:

Support for AmpereOne family
Ampere's newest processor, AmpereOne, has architecture-specific build options to improve performance through better code generation. This PR is aimed to detect software built for the Arm Neoverse series of processors and recommend options for AmpereOne support.

Add detection for meson build files
This PR support detects meson build files for missing AmpereOne support.

Other changes
Extend other arch list with loongarch64, riscv64, sandybridge, zen, etc to reduce noise.
UT cases extended.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Comment by binh-ampere** [comment]
> Bin, I would recommend the following text:
> 
> Support for AmpereOne family Ampere's newest processor, AmpereOne, has architecture-specific build options to improve performance through better code generation. This PR is aimed to detect software built for the Arm Neoverse series of processors and recommend options for AmpereOne support.
> 
> Add detection for meson build files This PR support detects meson build files for missing AmpereOne support.
> 
> Other changes Extend other arch list with loongarch64, riscv64, sandybridge, zen, etc to reduce noise. UT cases extended.
> 
> By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

Thanks @naren-ampere , summary updated.

**Comment by davidz-ampere** [comment]
Looks good for me.

**Review by davidz-ampere — APPROVED** [review]
Looks good for me. 
Thanks, Bin!

**Pull request merged**
